id: P006806
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:23:57.790099
source_metadata:
  id: bdr:W8LS20078
  title: ཕུར་པའི་ཆོས་སྐོར།
  author: ''
  volumes:
    3d3ba3b81ed742bfb81f78e0030cc279:
      image_group_id: I8LS20080
      title: ''
      volume_number: 1
      total_pages: 153
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
